language: php

dist: precise

addons:
  postgresql: 9.4
  mysql: 5.7

  apt:
    packages:
      - graphviz
      - oracle-java8-set-default

services:
  - postgresql
  - mysql
  - redis
  - rabbitmq

sudo: required

install:
  - sudo apt-get update && sudo apt-get install oracle-java8-installer
  - java -version
  - config/Shared/ci/travis/install_elasticsearch.sh
