language: php

dist: precise

addons:
  postgresql: 9.4
  mysql: 5.7

  apt:
    packages:
      - graphviz

services:
  - postgresql
  - mysql
  - redis
  - rabbitmq

sudo: required

env:
  global:
    - JAVA_HOME=/usr

install:
  - java -version
  - sudo apt-get update && sudo apt-get install oracle-java8-installer && sudo apt-get install oracle-java8-set-default
  - java -version
  - config/Shared/ci/travis/install_elasticsearch.sh
